FROM node:18-alpine AS builder

WORKDIR /app
 

COPY package.json ./
RUN npm install

COPY proto/ ./proto/ 

FROM nginx:alpine
COPY --from=builder /app/*.js /usr/share/nginx/html/
COPY index.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]