// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: car.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------
// Generic empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_car_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{0}
}

// ---------------------------------------------------
// Static car information - sent once at check-in
type CarInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Team          string                 `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Power         float32                `protobuf:"fixed32,3,opt,name=power,proto3" json:"power,omitempty"` // Engine power (0-100 scale)
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`   // Car color for display
	Driver        string                 `protobuf:"bytes,5,opt,name=driver,proto3" json:"driver,omitempty"` // Driver name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarInfo) Reset() {
	*x = CarInfo{}
	mi := &file_car_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarInfo) ProtoMessage() {}

func (x *CarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarInfo.ProtoReflect.Descriptor instead.
func (*CarInfo) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{1}
}

func (x *CarInfo) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *CarInfo) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *CarInfo) GetPower() float32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *CarInfo) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CarInfo) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

// ---------------------------------------------------
// Player input controls - sent continuously by clients
type PlayerInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CarId     string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	AuthToken string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // Secret token to authenticate the player
	// Control inputs (normalized -1.0 to 1.0 or 0.0 to 1.0)
	Steering      float32 `protobuf:"fixed32,3,opt,name=steering,proto3" json:"steering,omitempty"`  // -1.0 (full left) to 1.0 (full right)
	Throttle      float32 `protobuf:"fixed32,4,opt,name=throttle,proto3" json:"throttle,omitempty"`  // 0.0 to 1.0 (acceleration)
	Brake         float32 `protobuf:"fixed32,5,opt,name=brake,proto3" json:"brake,omitempty"`        // 0.0 to 1.0 (braking force)
	Boost         bool    `protobuf:"varint,6,opt,name=boost,proto3" json:"boost,omitempty"`         // Boost/nitro button (optional)
	Timestamp     int64   `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Client send time in ms
	Sequence      int32   `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`   // Incrementing sequence number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_car_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerInput) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *PlayerInput) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *PlayerInput) GetSteering() float32 {
	if x != nil {
		return x.Steering
	}
	return 0
}

func (x *PlayerInput) GetThrottle() float32 {
	if x != nil {
		return x.Throttle
	}
	return 0
}

func (x *PlayerInput) GetBrake() float32 {
	if x != nil {
		return x.Brake
	}
	return 0
}

func (x *PlayerInput) GetBoost() bool {
	if x != nil {
		return x.Boost
	}
	return false
}

func (x *PlayerInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PlayerInput) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// ---------------------------------------------------
// Server response to PlayerInput
type InputAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                       // True if input was accepted
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                            // If rejected, reason (auth, race state, etc.)
	ServerTime    int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // Server unix timestamp in ms
	GameTick      int64                  `protobuf:"varint,4,opt,name=game_tick,json=gameTick,proto3" json:"game_tick,omitempty"`       // Game loop tick number when input was processed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputAck) Reset() {
	*x = InputAck{}
	mi := &file_car_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputAck) ProtoMessage() {}

func (x *InputAck) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputAck.ProtoReflect.Descriptor instead.
func (*InputAck) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{3}
}

func (x *InputAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *InputAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InputAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *InputAck) GetGameTick() int64 {
	if x != nil {
		return x.GameTick
	}
	return 0
}

// ---------------------------------------------------
// Dynamic car state during race
type CarState struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CarId     string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	X         float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Heading   float32                `protobuf:"fixed32,4,opt,name=heading,proto3" json:"heading,omitempty"` // Direction in degrees (0-360)
	Speed     float32                `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`     // Current speed
	Lap       int32                  `protobuf:"varint,6,opt,name=lap,proto3" json:"lap,omitempty"`          // Current lap number
	Timestamp int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional: show last input for debugging/spectating
	CurrentSteering float32 `protobuf:"fixed32,8,opt,name=current_steering,json=currentSteering,proto3" json:"current_steering,omitempty"`
	CurrentThrottle float32 `protobuf:"fixed32,9,opt,name=current_throttle,json=currentThrottle,proto3" json:"current_throttle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CarState) Reset() {
	*x = CarState{}
	mi := &file_car_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarState) ProtoMessage() {}

func (x *CarState) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarState.ProtoReflect.Descriptor instead.
func (*CarState) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{4}
}

func (x *CarState) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *CarState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CarState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CarState) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *CarState) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *CarState) GetLap() int32 {
	if x != nil {
		return x.Lap
	}
	return 0
}

func (x *CarState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CarState) GetCurrentSteering() float32 {
	if x != nil {
		return x.CurrentSteering
	}
	return 0
}

func (x *CarState) GetCurrentThrottle() float32 {
	if x != nil {
		return x.CurrentThrottle
	}
	return 0
}

// ---------------------------------------------------
// Race status information
type RaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                // "waiting", "racing", "finished"
	TotalLaps     int32                  `protobuf:"varint,2,opt,name=total_laps,json=totalLaps,proto3" json:"total_laps,omitempty"`        // Total laps in race
	RaceTime      int64                  `protobuf:"varint,3,opt,name=race_time,json=raceTime,proto3" json:"race_time,omitempty"`           // Elapsed time in milliseconds
	LeaderCarId   string                 `protobuf:"bytes,4,opt,name=leader_car_id,json=leaderCarId,proto3" json:"leader_car_id,omitempty"` // Current race leader
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceStatus) Reset() {
	*x = RaceStatus{}
	mi := &file_car_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceStatus) ProtoMessage() {}

func (x *RaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceStatus.ProtoReflect.Descriptor instead.
func (*RaceStatus) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{5}
}

func (x *RaceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RaceStatus) GetTotalLaps() int32 {
	if x != nil {
		return x.TotalLaps
	}
	return 0
}

func (x *RaceStatus) GetRaceTime() int64 {
	if x != nil {
		return x.RaceTime
	}
	return 0
}

func (x *RaceStatus) GetLeaderCarId() string {
	if x != nil {
		return x.LeaderCarId
	}
	return ""
}

// ---------------------------------------------------
// Check-in message with all static car information
type CheckIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*CarInfo             `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIn) Reset() {
	*x = CheckIn{}
	mi := &file_car_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIn) ProtoMessage() {}

func (x *CheckIn) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIn.ProtoReflect.Descriptor instead.
func (*CheckIn) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{6}
}

func (x *CheckIn) GetCars() []*CarInfo {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *CheckIn) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ---------------------------------------------------
// Race update message with status and all car positions
type RaceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaceStatus    *RaceStatus            `protobuf:"bytes,1,opt,name=race_status,json=raceStatus,proto3" json:"race_status,omitempty"`
	Cars          []*CarState            `protobuf:"bytes,2,rep,name=cars,proto3" json:"cars,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	GameTick      int64                  `protobuf:"varint,4,opt,name=game_tick,json=gameTick,proto3" json:"game_tick,omitempty"` // Added for lag tracking/debugging
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceData) Reset() {
	*x = RaceData{}
	mi := &file_car_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceData) ProtoMessage() {}

func (x *RaceData) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceData.ProtoReflect.Descriptor instead.
func (*RaceData) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{7}
}

func (x *RaceData) GetRaceStatus() *RaceStatus {
	if x != nil {
		return x.RaceStatus
	}
	return nil
}

func (x *RaceData) GetCars() []*CarState {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *RaceData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RaceData) GetGameTick() int64 {
	if x != nil {
		return x.GameTick
	}
	return 0
}

// ---------------------------------------------------
// Union message for streaming different types
type RaceUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*RaceUpdate_CheckIn
	//	*RaceUpdate_RaceData
	Update        isRaceUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaceUpdate) Reset() {
	*x = RaceUpdate{}
	mi := &file_car_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaceUpdate) ProtoMessage() {}

func (x *RaceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaceUpdate.ProtoReflect.Descriptor instead.
func (*RaceUpdate) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{8}
}

func (x *RaceUpdate) GetUpdate() isRaceUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *RaceUpdate) GetCheckIn() *CheckIn {
	if x != nil {
		if x, ok := x.Update.(*RaceUpdate_CheckIn); ok {
			return x.CheckIn
		}
	}
	return nil
}

func (x *RaceUpdate) GetRaceData() *RaceData {
	if x != nil {
		if x, ok := x.Update.(*RaceUpdate_RaceData); ok {
			return x.RaceData
		}
	}
	return nil
}

type isRaceUpdate_Update interface {
	isRaceUpdate_Update()
}

type RaceUpdate_CheckIn struct {
	CheckIn *CheckIn `protobuf:"bytes,1,opt,name=check_in,json=checkIn,proto3,oneof"` // Sent once at connection start
}

type RaceUpdate_RaceData struct {
	RaceData *RaceData `protobuf:"bytes,2,opt,name=race_data,json=raceData,proto3,oneof"` // Sent continuously during race
}

func (*RaceUpdate_CheckIn) isRaceUpdate_Update() {}

func (*RaceUpdate_RaceData) isRaceUpdate_Update() {}

// ---------------------------------------------------
// Optional: Registration/authentication message
type RegisterPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // Or use external auth service
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPlayer) Reset() {
	*x = RegisterPlayer{}
	mi := &file_car_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPlayer) ProtoMessage() {}

func (x *RegisterPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPlayer.ProtoReflect.Descriptor instead.
func (*RegisterPlayer) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterPlayer) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *RegisterPlayer) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *RegisterPlayer) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AuthToken     string                 `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"` // Token to use in PlayerInput
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                      // Error or success message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_car_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_car_proto protoreflect.FileDescriptor

const file_car_proto_rawDesc = "" +
	"\n" +
	"\tcar.proto\x12\x03car\"\a\n" +
	"\x05Empty\"x\n" +
	"\aCarInfo\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x12\n" +
	"\x04team\x18\x02 \x01(\tR\x04team\x12\x14\n" +
	"\x05power\x18\x03 \x01(\x02R\x05power\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x16\n" +
	"\x06driver\x18\x05 \x01(\tR\x06driver\"\xe1\x01\n" +
	"\vPlayerInput\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x1a\n" +
	"\bsteering\x18\x03 \x01(\x02R\bsteering\x12\x1a\n" +
	"\bthrottle\x18\x04 \x01(\x02R\bthrottle\x12\x14\n" +
	"\x05brake\x18\x05 \x01(\x02R\x05brake\x12\x14\n" +
	"\x05boost\x18\x06 \x01(\bR\x05boost\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x05R\bsequence\"|\n" +
	"\bInputAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12\x1b\n" +
	"\tgame_tick\x18\x04 \x01(\x03R\bgameTick\"\xf3\x01\n" +
	"\bCarState\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x02R\aheading\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x02R\x05speed\x12\x10\n" +
	"\x03lap\x18\x06 \x01(\x05R\x03lap\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12)\n" +
	"\x10current_steering\x18\b \x01(\x02R\x0fcurrentSteering\x12)\n" +
	"\x10current_throttle\x18\t \x01(\x02R\x0fcurrentThrottle\"\x84\x01\n" +
	"\n" +
	"RaceStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"total_laps\x18\x02 \x01(\x05R\ttotalLaps\x12\x1b\n" +
	"\trace_time\x18\x03 \x01(\x03R\braceTime\x12\"\n" +
	"\rleader_car_id\x18\x04 \x01(\tR\vleaderCarId\"I\n" +
	"\aCheckIn\x12 \n" +
	"\x04cars\x18\x01 \x03(\v2\f.car.CarInfoR\x04cars\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\x9a\x01\n" +
	"\bRaceData\x120\n" +
	"\vrace_status\x18\x01 \x01(\v2\x0f.car.RaceStatusR\n" +
	"raceStatus\x12!\n" +
	"\x04cars\x18\x02 \x03(\v2\r.car.CarStateR\x04cars\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tgame_tick\x18\x04 \x01(\x03R\bgameTick\"o\n" +
	"\n" +
	"RaceUpdate\x12)\n" +
	"\bcheck_in\x18\x01 \x01(\v2\f.car.CheckInH\x00R\acheckIn\x12,\n" +
	"\trace_data\x18\x02 \x01(\v2\r.car.RaceDataH\x00R\braceDataB\b\n" +
	"\x06update\"d\n" +
	"\x0eRegisterPlayer\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"e\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\tR\tauthToken\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2t\n" +
	"\n" +
	"CarService\x122\n" +
	"\x11StreamRaceUpdates\x12\n" +
	".car.Empty\x1a\x0f.car.RaceUpdate0\x01\x122\n" +
	"\x0fSendPlayerInput\x12\x10.car.PlayerInput\x1a\r.car.InputAckB\tZ\a./protob\x06proto3"

var (
	file_car_proto_rawDescOnce sync.Once
	file_car_proto_rawDescData []byte
)

func file_car_proto_rawDescGZIP() []byte {
	file_car_proto_rawDescOnce.Do(func() {
		file_car_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_car_proto_rawDesc), len(file_car_proto_rawDesc)))
	})
	return file_car_proto_rawDescData
}

var file_car_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_car_proto_goTypes = []any{
	(*Empty)(nil),            // 0: car.Empty
	(*CarInfo)(nil),          // 1: car.CarInfo
	(*PlayerInput)(nil),      // 2: car.PlayerInput
	(*InputAck)(nil),         // 3: car.InputAck
	(*CarState)(nil),         // 4: car.CarState
	(*RaceStatus)(nil),       // 5: car.RaceStatus
	(*CheckIn)(nil),          // 6: car.CheckIn
	(*RaceData)(nil),         // 7: car.RaceData
	(*RaceUpdate)(nil),       // 8: car.RaceUpdate
	(*RegisterPlayer)(nil),   // 9: car.RegisterPlayer
	(*RegisterResponse)(nil), // 10: car.RegisterResponse
}
var file_car_proto_depIdxs = []int32{
	1, // 0: car.CheckIn.cars:type_name -> car.CarInfo
	5, // 1: car.RaceData.race_status:type_name -> car.RaceStatus
	4, // 2: car.RaceData.cars:type_name -> car.CarState
	6, // 3: car.RaceUpdate.check_in:type_name -> car.CheckIn
	7, // 4: car.RaceUpdate.race_data:type_name -> car.RaceData
	0, // 5: car.CarService.StreamRaceUpdates:input_type -> car.Empty
	2, // 6: car.CarService.SendPlayerInput:input_type -> car.PlayerInput
	8, // 7: car.CarService.StreamRaceUpdates:output_type -> car.RaceUpdate
	3, // 8: car.CarService.SendPlayerInput:output_type -> car.InputAck
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_car_proto_init() }
func file_car_proto_init() {
	if File_car_proto != nil {
		return
	}
	file_car_proto_msgTypes[8].OneofWrappers = []any{
		(*RaceUpdate_CheckIn)(nil),
		(*RaceUpdate_RaceData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_car_proto_rawDesc), len(file_car_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_car_proto_goTypes,
		DependencyIndexes: file_car_proto_depIdxs,
		MessageInfos:      file_car_proto_msgTypes,
	}.Build()
	File_car_proto = out.File
	file_car_proto_goTypes = nil
	file_car_proto_depIdxs = nil
}
