/**
 * @fileoverview gRPC-Web generated client stub for car
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.2
// source: car.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.car = require('./car_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.car.CarServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.car.CarServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.car.Empty,
 *   !proto.car.CarPosition>}
 */
const methodDescriptor_CarService_StreamCarPosition = new grpc.web.MethodDescriptor(
  '/car.CarService/StreamCarPosition',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.car.Empty,
  proto.car.CarPosition,
  /**
   * @param {!proto.car.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.car.CarPosition.deserializeBinary
);


/**
 * @param {!proto.car.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.car.CarPosition>}
 *     The XHR Node Readable Stream
 */
proto.car.CarServiceClient.prototype.streamCarPosition =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/car.CarService/StreamCarPosition',
      request,
      metadata || {},
      methodDescriptor_CarService_StreamCarPosition);
};


/**
 * @param {!proto.car.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.car.CarPosition>}
 *     The XHR Node Readable Stream
 */
proto.car.CarServicePromiseClient.prototype.streamCarPosition =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/car.CarService/StreamCarPosition',
      request,
      metadata || {},
      methodDescriptor_CarService_StreamCarPosition);
};


module.exports = proto.car;

