// source: car.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.car.CarInfo', null, global);
goog.exportSymbol('proto.car.CarState', null, global);
goog.exportSymbol('proto.car.CheckIn', null, global);
goog.exportSymbol('proto.car.Empty', null, global);
goog.exportSymbol('proto.car.RaceData', null, global);
goog.exportSymbol('proto.car.RaceStatus', null, global);
goog.exportSymbol('proto.car.RaceUpdate', null, global);
goog.exportSymbol('proto.car.RaceUpdate.UpdateCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.Empty.displayName = 'proto.car.Empty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CarInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.CarInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CarInfo.displayName = 'proto.car.CarInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CarState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.CarState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CarState.displayName = 'proto.car.CarState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.RaceStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.RaceStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.RaceStatus.displayName = 'proto.car.RaceStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CheckIn = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.car.CheckIn.repeatedFields_, null);
};
goog.inherits(proto.car.CheckIn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CheckIn.displayName = 'proto.car.CheckIn';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.RaceData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.car.RaceData.repeatedFields_, null);
};
goog.inherits(proto.car.RaceData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.RaceData.displayName = 'proto.car.RaceData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.RaceUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.car.RaceUpdate.oneofGroups_);
};
goog.inherits(proto.car.RaceUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.RaceUpdate.displayName = 'proto.car.RaceUpdate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.car.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.Empty}
 */
proto.car.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.Empty;
  return proto.car.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.Empty}
 */
proto.car.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CarInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CarInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CarInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
team: jspb.Message.getFieldWithDefault(msg, 2, ""),
power: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
color: jspb.Message.getFieldWithDefault(msg, 4, ""),
driver: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CarInfo}
 */
proto.car.CarInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CarInfo;
  return proto.car.CarInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CarInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CarInfo}
 */
proto.car.CarInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeam(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPower(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setColor(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDriver(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CarInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CarInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CarInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTeam();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPower();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getColor();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDriver();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.CarInfo.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string team = 2;
 * @return {string}
 */
proto.car.CarInfo.prototype.getTeam = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setTeam = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float power = 3;
 * @return {number}
 */
proto.car.CarInfo.prototype.getPower = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setPower = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string color = 4;
 * @return {string}
 */
proto.car.CarInfo.prototype.getColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setColor = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string driver = 5;
 * @return {string}
 */
proto.car.CarInfo.prototype.getDriver = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setDriver = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CarState.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CarState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CarState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarState.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
x: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
y: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
heading: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
speed: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
lap: jspb.Message.getFieldWithDefault(msg, 6, 0),
timestamp: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CarState}
 */
proto.car.CarState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CarState;
  return proto.car.CarState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CarState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CarState}
 */
proto.car.CarState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHeading(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSpeed(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLap(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CarState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CarState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CarState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getHeading();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getSpeed();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getLap();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.CarState.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float x = 2;
 * @return {number}
 */
proto.car.CarState.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float y = 3;
 * @return {number}
 */
proto.car.CarState.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float heading = 4;
 * @return {number}
 */
proto.car.CarState.prototype.getHeading = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setHeading = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float speed = 5;
 * @return {number}
 */
proto.car.CarState.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setSpeed = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional int32 lap = 6;
 * @return {number}
 */
proto.car.CarState.prototype.getLap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setLap = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 timestamp = 7;
 * @return {number}
 */
proto.car.CarState.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.RaceStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.car.RaceStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.RaceStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getFieldWithDefault(msg, 1, ""),
totalLaps: jspb.Message.getFieldWithDefault(msg, 2, 0),
raceTime: jspb.Message.getFieldWithDefault(msg, 3, 0),
leaderCarId: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.RaceStatus}
 */
proto.car.RaceStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.RaceStatus;
  return proto.car.RaceStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.RaceStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.RaceStatus}
 */
proto.car.RaceStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalLaps(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRaceTime(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLeaderCarId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.RaceStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.RaceStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.RaceStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTotalLaps();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getRaceTime();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getLeaderCarId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
proto.car.RaceStatus.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.RaceStatus} returns this
 */
proto.car.RaceStatus.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 total_laps = 2;
 * @return {number}
 */
proto.car.RaceStatus.prototype.getTotalLaps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceStatus} returns this
 */
proto.car.RaceStatus.prototype.setTotalLaps = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 race_time = 3;
 * @return {number}
 */
proto.car.RaceStatus.prototype.getRaceTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceStatus} returns this
 */
proto.car.RaceStatus.prototype.setRaceTime = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string leader_car_id = 4;
 * @return {string}
 */
proto.car.RaceStatus.prototype.getLeaderCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.RaceStatus} returns this
 */
proto.car.RaceStatus.prototype.setLeaderCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.car.CheckIn.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CheckIn.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CheckIn.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CheckIn} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CheckIn.toObject = function(includeInstance, msg) {
  var f, obj = {
carsList: jspb.Message.toObjectList(msg.getCarsList(),
    proto.car.CarInfo.toObject, includeInstance),
timestamp: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CheckIn}
 */
proto.car.CheckIn.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CheckIn;
  return proto.car.CheckIn.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CheckIn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CheckIn}
 */
proto.car.CheckIn.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.car.CarInfo;
      reader.readMessage(value,proto.car.CarInfo.deserializeBinaryFromReader);
      msg.addCars(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CheckIn.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CheckIn.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CheckIn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CheckIn.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.car.CarInfo.serializeBinaryToWriter
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * repeated CarInfo cars = 1;
 * @return {!Array<!proto.car.CarInfo>}
 */
proto.car.CheckIn.prototype.getCarsList = function() {
  return /** @type{!Array<!proto.car.CarInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.CarInfo, 1));
};


/**
 * @param {!Array<!proto.car.CarInfo>} value
 * @return {!proto.car.CheckIn} returns this
*/
proto.car.CheckIn.prototype.setCarsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.car.CarInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.CarInfo}
 */
proto.car.CheckIn.prototype.addCars = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.car.CarInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.CheckIn} returns this
 */
proto.car.CheckIn.prototype.clearCarsList = function() {
  return this.setCarsList([]);
};


/**
 * optional int64 timestamp = 2;
 * @return {number}
 */
proto.car.CheckIn.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CheckIn} returns this
 */
proto.car.CheckIn.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.car.RaceData.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.RaceData.prototype.toObject = function(opt_includeInstance) {
  return proto.car.RaceData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.RaceData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceData.toObject = function(includeInstance, msg) {
  var f, obj = {
raceStatus: (f = msg.getRaceStatus()) && proto.car.RaceStatus.toObject(includeInstance, f),
carsList: jspb.Message.toObjectList(msg.getCarsList(),
    proto.car.CarState.toObject, includeInstance),
timestamp: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.RaceData}
 */
proto.car.RaceData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.RaceData;
  return proto.car.RaceData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.RaceData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.RaceData}
 */
proto.car.RaceData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.car.RaceStatus;
      reader.readMessage(value,proto.car.RaceStatus.deserializeBinaryFromReader);
      msg.setRaceStatus(value);
      break;
    case 2:
      var value = new proto.car.CarState;
      reader.readMessage(value,proto.car.CarState.deserializeBinaryFromReader);
      msg.addCars(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.RaceData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.RaceData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.RaceData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRaceStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.car.RaceStatus.serializeBinaryToWriter
    );
  }
  f = message.getCarsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.car.CarState.serializeBinaryToWriter
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional RaceStatus race_status = 1;
 * @return {?proto.car.RaceStatus}
 */
proto.car.RaceData.prototype.getRaceStatus = function() {
  return /** @type{?proto.car.RaceStatus} */ (
    jspb.Message.getWrapperField(this, proto.car.RaceStatus, 1));
};


/**
 * @param {?proto.car.RaceStatus|undefined} value
 * @return {!proto.car.RaceData} returns this
*/
proto.car.RaceData.prototype.setRaceStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.car.RaceData} returns this
 */
proto.car.RaceData.prototype.clearRaceStatus = function() {
  return this.setRaceStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.car.RaceData.prototype.hasRaceStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated CarState cars = 2;
 * @return {!Array<!proto.car.CarState>}
 */
proto.car.RaceData.prototype.getCarsList = function() {
  return /** @type{!Array<!proto.car.CarState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.CarState, 2));
};


/**
 * @param {!Array<!proto.car.CarState>} value
 * @return {!proto.car.RaceData} returns this
*/
proto.car.RaceData.prototype.setCarsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.car.CarState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.CarState}
 */
proto.car.RaceData.prototype.addCars = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.car.CarState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.RaceData} returns this
 */
proto.car.RaceData.prototype.clearCarsList = function() {
  return this.setCarsList([]);
};


/**
 * optional int64 timestamp = 3;
 * @return {number}
 */
proto.car.RaceData.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceData} returns this
 */
proto.car.RaceData.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.car.RaceUpdate.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.car.RaceUpdate.UpdateCase = {
  UPDATE_NOT_SET: 0,
  CHECK_IN: 1,
  RACE_DATA: 2
};

/**
 * @return {proto.car.RaceUpdate.UpdateCase}
 */
proto.car.RaceUpdate.prototype.getUpdateCase = function() {
  return /** @type {proto.car.RaceUpdate.UpdateCase} */(jspb.Message.computeOneofCase(this, proto.car.RaceUpdate.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.RaceUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.car.RaceUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.RaceUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
checkIn: (f = msg.getCheckIn()) && proto.car.CheckIn.toObject(includeInstance, f),
raceData: (f = msg.getRaceData()) && proto.car.RaceData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.RaceUpdate}
 */
proto.car.RaceUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.RaceUpdate;
  return proto.car.RaceUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.RaceUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.RaceUpdate}
 */
proto.car.RaceUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.car.CheckIn;
      reader.readMessage(value,proto.car.CheckIn.deserializeBinaryFromReader);
      msg.setCheckIn(value);
      break;
    case 2:
      var value = new proto.car.RaceData;
      reader.readMessage(value,proto.car.RaceData.deserializeBinaryFromReader);
      msg.setRaceData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.RaceUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.RaceUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.RaceUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCheckIn();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.car.CheckIn.serializeBinaryToWriter
    );
  }
  f = message.getRaceData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.car.RaceData.serializeBinaryToWriter
    );
  }
};


/**
 * optional CheckIn check_in = 1;
 * @return {?proto.car.CheckIn}
 */
proto.car.RaceUpdate.prototype.getCheckIn = function() {
  return /** @type{?proto.car.CheckIn} */ (
    jspb.Message.getWrapperField(this, proto.car.CheckIn, 1));
};


/**
 * @param {?proto.car.CheckIn|undefined} value
 * @return {!proto.car.RaceUpdate} returns this
*/
proto.car.RaceUpdate.prototype.setCheckIn = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.car.RaceUpdate.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.clearCheckIn = function() {
  return this.setCheckIn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.car.RaceUpdate.prototype.hasCheckIn = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional RaceData race_data = 2;
 * @return {?proto.car.RaceData}
 */
proto.car.RaceUpdate.prototype.getRaceData = function() {
  return /** @type{?proto.car.RaceData} */ (
    jspb.Message.getWrapperField(this, proto.car.RaceData, 2));
};


/**
 * @param {?proto.car.RaceData|undefined} value
 * @return {!proto.car.RaceUpdate} returns this
*/
proto.car.RaceUpdate.prototype.setRaceData = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.car.RaceUpdate.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.clearRaceData = function() {
  return this.setRaceData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.car.RaceUpdate.prototype.hasRaceData = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.car);
