/**
 * @fileoverview gRPC-Web generated client stub for car
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.2
// source: car.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.car = require('./car_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.car.CarServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.car.CarServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.car.Empty,
 *   !proto.car.RaceUpdate>}
 */
const methodDescriptor_CarService_StreamRaceUpdates = new grpc.web.MethodDescriptor(
  '/car.CarService/StreamRaceUpdates',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.car.Empty,
  proto.car.RaceUpdate,
  /**
   * @param {!proto.car.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.car.RaceUpdate.deserializeBinary
);


/**
 * @param {!proto.car.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.car.RaceUpdate>}
 *     The XHR Node Readable Stream
 */
proto.car.CarServiceClient.prototype.streamRaceUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/car.CarService/StreamRaceUpdates',
      request,
      metadata || {},
      methodDescriptor_CarService_StreamRaceUpdates);
};


/**
 * @param {!proto.car.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.car.RaceUpdate>}
 *     The XHR Node Readable Stream
 */
proto.car.CarServicePromiseClient.prototype.streamRaceUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/car.CarService/StreamRaceUpdates',
      request,
      metadata || {},
      methodDescriptor_CarService_StreamRaceUpdates);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.car.PlayerInput,
 *   !proto.car.InputAck>}
 */
const methodDescriptor_CarService_SendPlayerInput = new grpc.web.MethodDescriptor(
  '/car.CarService/SendPlayerInput',
  grpc.web.MethodType.UNARY,
  proto.car.PlayerInput,
  proto.car.InputAck,
  /**
   * @param {!proto.car.PlayerInput} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.car.InputAck.deserializeBinary
);


/**
 * @param {!proto.car.PlayerInput} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.car.InputAck)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.car.InputAck>|undefined}
 *     The XHR Node Readable Stream
 */
proto.car.CarServiceClient.prototype.sendPlayerInput =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/car.CarService/SendPlayerInput',
      request,
      metadata || {},
      methodDescriptor_CarService_SendPlayerInput,
      callback);
};


/**
 * @param {!proto.car.PlayerInput} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.car.InputAck>}
 *     Promise that resolves to the response
 */
proto.car.CarServicePromiseClient.prototype.sendPlayerInput =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/car.CarService/SendPlayerInput',
      request,
      metadata || {},
      methodDescriptor_CarService_SendPlayerInput);
};


module.exports = proto.car;

