// source: car.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.car.CarInfo', null, global);
goog.exportSymbol('proto.car.CarInterval', null, global);
goog.exportSymbol('proto.car.CarPenalty', null, global);
goog.exportSymbol('proto.car.CarState', null, global);
goog.exportSymbol('proto.car.CarStatus', null, global);
goog.exportSymbol('proto.car.CheckInResponse', null, global);
goog.exportSymbol('proto.car.Empty', null, global);
goog.exportSymbol('proto.car.InputAck', null, global);
goog.exportSymbol('proto.car.PlayerInput', null, global);
goog.exportSymbol('proto.car.Point3D', null, global);
goog.exportSymbol('proto.car.RaceDescription', null, global);
goog.exportSymbol('proto.car.RaceStatus', null, global);
goog.exportSymbol('proto.car.RaceType', null, global);
goog.exportSymbol('proto.car.RaceUpdate', null, global);
goog.exportSymbol('proto.car.RegisterPlayer', null, global);
goog.exportSymbol('proto.car.TrackInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.Empty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.Empty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.Empty.displayName = 'proto.car.Empty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.Point3D = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.Point3D, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.Point3D.displayName = 'proto.car.Point3D';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.TrackInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.car.TrackInfo.repeatedFields_, null);
};
goog.inherits(proto.car.TrackInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.TrackInfo.displayName = 'proto.car.TrackInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.RaceDescription = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.RaceDescription, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.RaceDescription.displayName = 'proto.car.RaceDescription';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CarInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.CarInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CarInfo.displayName = 'proto.car.CarInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.RegisterPlayer = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.RegisterPlayer, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.RegisterPlayer.displayName = 'proto.car.RegisterPlayer';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CheckInResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.CheckInResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CheckInResponse.displayName = 'proto.car.CheckInResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.PlayerInput = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.PlayerInput, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.PlayerInput.displayName = 'proto.car.PlayerInput';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.InputAck = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.InputAck, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.InputAck.displayName = 'proto.car.InputAck';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CarState = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.CarState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CarState.displayName = 'proto.car.CarState';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CarPenalty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.CarPenalty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CarPenalty.displayName = 'proto.car.CarPenalty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.RaceStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.RaceStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.RaceStatus.displayName = 'proto.car.RaceStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.CarInterval = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.car.CarInterval, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.CarInterval.displayName = 'proto.car.CarInterval';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.car.RaceUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.car.RaceUpdate.repeatedFields_, null);
};
goog.inherits(proto.car.RaceUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.car.RaceUpdate.displayName = 'proto.car.RaceUpdate';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.Empty.prototype.toObject = function(opt_includeInstance) {
  return proto.car.Empty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.Empty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.Empty.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.Empty}
 */
proto.car.Empty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.Empty;
  return proto.car.Empty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.Empty}
 */
proto.car.Empty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.Empty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.Empty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.Empty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.Point3D.prototype.toObject = function(opt_includeInstance) {
  return proto.car.Point3D.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.Point3D} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.Point3D.toObject = function(includeInstance, msg) {
  var f, obj = {
x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
z: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.Point3D}
 */
proto.car.Point3D.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.Point3D;
  return proto.car.Point3D.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.Point3D} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.Point3D}
 */
proto.car.Point3D.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setZ(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.Point3D.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.Point3D.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.Point3D} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.Point3D.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getZ();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
};


/**
 * optional float x = 1;
 * @return {number}
 */
proto.car.Point3D.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.Point3D} returns this
 */
proto.car.Point3D.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional float y = 2;
 * @return {number}
 */
proto.car.Point3D.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.Point3D} returns this
 */
proto.car.Point3D.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float z = 3;
 * @return {number}
 */
proto.car.Point3D.prototype.getZ = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.Point3D} returns this
 */
proto.car.Point3D.prototype.setZ = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.car.TrackInfo.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.TrackInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.car.TrackInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.TrackInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.TrackInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
trackId: jspb.Message.getFieldWithDefault(msg, 1, ""),
name: jspb.Message.getFieldWithDefault(msg, 2, ""),
leftBoundaryList: jspb.Message.toObjectList(msg.getLeftBoundaryList(),
    proto.car.Point3D.toObject, includeInstance),
rightBoundaryList: jspb.Message.toObjectList(msg.getRightBoundaryList(),
    proto.car.Point3D.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.TrackInfo}
 */
proto.car.TrackInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.TrackInfo;
  return proto.car.TrackInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.TrackInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.TrackInfo}
 */
proto.car.TrackInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrackId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.car.Point3D;
      reader.readMessage(value,proto.car.Point3D.deserializeBinaryFromReader);
      msg.addLeftBoundary(value);
      break;
    case 4:
      var value = new proto.car.Point3D;
      reader.readMessage(value,proto.car.Point3D.deserializeBinaryFromReader);
      msg.addRightBoundary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.TrackInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.TrackInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.TrackInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.TrackInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrackId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLeftBoundaryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.car.Point3D.serializeBinaryToWriter
    );
  }
  f = message.getRightBoundaryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.car.Point3D.serializeBinaryToWriter
    );
  }
};


/**
 * optional string track_id = 1;
 * @return {string}
 */
proto.car.TrackInfo.prototype.getTrackId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.TrackInfo} returns this
 */
proto.car.TrackInfo.prototype.setTrackId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.car.TrackInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.TrackInfo} returns this
 */
proto.car.TrackInfo.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Point3D left_boundary = 3;
 * @return {!Array<!proto.car.Point3D>}
 */
proto.car.TrackInfo.prototype.getLeftBoundaryList = function() {
  return /** @type{!Array<!proto.car.Point3D>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.Point3D, 3));
};


/**
 * @param {!Array<!proto.car.Point3D>} value
 * @return {!proto.car.TrackInfo} returns this
*/
proto.car.TrackInfo.prototype.setLeftBoundaryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.car.Point3D=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.Point3D}
 */
proto.car.TrackInfo.prototype.addLeftBoundary = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.car.Point3D, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.TrackInfo} returns this
 */
proto.car.TrackInfo.prototype.clearLeftBoundaryList = function() {
  return this.setLeftBoundaryList([]);
};


/**
 * repeated Point3D right_boundary = 4;
 * @return {!Array<!proto.car.Point3D>}
 */
proto.car.TrackInfo.prototype.getRightBoundaryList = function() {
  return /** @type{!Array<!proto.car.Point3D>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.Point3D, 4));
};


/**
 * @param {!Array<!proto.car.Point3D>} value
 * @return {!proto.car.TrackInfo} returns this
*/
proto.car.TrackInfo.prototype.setRightBoundaryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.car.Point3D=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.Point3D}
 */
proto.car.TrackInfo.prototype.addRightBoundary = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.car.Point3D, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.TrackInfo} returns this
 */
proto.car.TrackInfo.prototype.clearRightBoundaryList = function() {
  return this.setRightBoundaryList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.RaceDescription.prototype.toObject = function(opt_includeInstance) {
  return proto.car.RaceDescription.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.RaceDescription} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceDescription.toObject = function(includeInstance, msg) {
  var f, obj = {
racetype: jspb.Message.getFieldWithDefault(msg, 1, 0),
laps: jspb.Message.getFieldWithDefault(msg, 100, 0),
time: jspb.Message.getFieldWithDefault(msg, 101, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.RaceDescription}
 */
proto.car.RaceDescription.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.RaceDescription;
  return proto.car.RaceDescription.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.RaceDescription} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.RaceDescription}
 */
proto.car.RaceDescription.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.car.RaceType} */ (reader.readEnum());
      msg.setRacetype(value);
      break;
    case 100:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLaps(value);
      break;
    case 101:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.RaceDescription.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.RaceDescription.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.RaceDescription} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceDescription.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRacetype();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getLaps();
  if (f !== 0) {
    writer.writeInt32(
      100,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeInt32(
      101,
      f
    );
  }
};


/**
 * optional RaceType racetype = 1;
 * @return {!proto.car.RaceType}
 */
proto.car.RaceDescription.prototype.getRacetype = function() {
  return /** @type {!proto.car.RaceType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.car.RaceType} value
 * @return {!proto.car.RaceDescription} returns this
 */
proto.car.RaceDescription.prototype.setRacetype = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int32 laps = 100;
 * @return {number}
 */
proto.car.RaceDescription.prototype.getLaps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 100, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceDescription} returns this
 */
proto.car.RaceDescription.prototype.setLaps = function(value) {
  return jspb.Message.setProto3IntField(this, 100, value);
};


/**
 * optional int32 time = 101;
 * @return {number}
 */
proto.car.RaceDescription.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 101, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceDescription} returns this
 */
proto.car.RaceDescription.prototype.setTime = function(value) {
  return jspb.Message.setProto3IntField(this, 101, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CarInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CarInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CarInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
power: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
weight: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CarInfo}
 */
proto.car.CarInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CarInfo;
  return proto.car.CarInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CarInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CarInfo}
 */
proto.car.CarInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPower(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setWeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CarInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CarInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CarInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPower();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.CarInfo.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float power = 3;
 * @return {number}
 */
proto.car.CarInfo.prototype.getPower = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setPower = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float weight = 4;
 * @return {number}
 */
proto.car.CarInfo.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarInfo} returns this
 */
proto.car.CarInfo.prototype.setWeight = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.RegisterPlayer.prototype.toObject = function(opt_includeInstance) {
  return proto.car.RegisterPlayer.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.RegisterPlayer} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RegisterPlayer.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
playerName: jspb.Message.getFieldWithDefault(msg, 2, ""),
password: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.RegisterPlayer}
 */
proto.car.RegisterPlayer.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.RegisterPlayer;
  return proto.car.RegisterPlayer.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.RegisterPlayer} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.RegisterPlayer}
 */
proto.car.RegisterPlayer.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayerName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.RegisterPlayer.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.RegisterPlayer.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.RegisterPlayer} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RegisterPlayer.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlayerName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.RegisterPlayer.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.RegisterPlayer} returns this
 */
proto.car.RegisterPlayer.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string player_name = 2;
 * @return {string}
 */
proto.car.RegisterPlayer.prototype.getPlayerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.RegisterPlayer} returns this
 */
proto.car.RegisterPlayer.prototype.setPlayerName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.car.RegisterPlayer.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.RegisterPlayer} returns this
 */
proto.car.RegisterPlayer.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CheckInResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CheckInResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CheckInResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CheckInResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
accepted: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
authToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
message: jspb.Message.getFieldWithDefault(msg, 3, ""),
isSpectator: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
track: (f = msg.getTrack()) && proto.car.TrackInfo.toObject(includeInstance, f),
race: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CheckInResponse}
 */
proto.car.CheckInResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CheckInResponse;
  return proto.car.CheckInResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CheckInResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CheckInResponse}
 */
proto.car.CheckInResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAccepted(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthToken(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsSpectator(value);
      break;
    case 5:
      var value = new proto.car.TrackInfo;
      reader.readMessage(value,proto.car.TrackInfo.deserializeBinaryFromReader);
      msg.setTrack(value);
      break;
    case 6:
      var value = /** @type {!proto.car.RaceType} */ (reader.readEnum());
      msg.setRace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CheckInResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CheckInResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CheckInResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CheckInResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccepted();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAuthToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIsSpectator();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getTrack();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.car.TrackInfo.serializeBinaryToWriter
    );
  }
  f = message.getRace();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional bool accepted = 1;
 * @return {boolean}
 */
proto.car.CheckInResponse.prototype.getAccepted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.car.CheckInResponse} returns this
 */
proto.car.CheckInResponse.prototype.setAccepted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string auth_token = 2;
 * @return {string}
 */
proto.car.CheckInResponse.prototype.getAuthToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CheckInResponse} returns this
 */
proto.car.CheckInResponse.prototype.setAuthToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string message = 3;
 * @return {string}
 */
proto.car.CheckInResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CheckInResponse} returns this
 */
proto.car.CheckInResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool is_spectator = 4;
 * @return {boolean}
 */
proto.car.CheckInResponse.prototype.getIsSpectator = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.car.CheckInResponse} returns this
 */
proto.car.CheckInResponse.prototype.setIsSpectator = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional TrackInfo track = 5;
 * @return {?proto.car.TrackInfo}
 */
proto.car.CheckInResponse.prototype.getTrack = function() {
  return /** @type{?proto.car.TrackInfo} */ (
    jspb.Message.getWrapperField(this, proto.car.TrackInfo, 5));
};


/**
 * @param {?proto.car.TrackInfo|undefined} value
 * @return {!proto.car.CheckInResponse} returns this
*/
proto.car.CheckInResponse.prototype.setTrack = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.car.CheckInResponse} returns this
 */
proto.car.CheckInResponse.prototype.clearTrack = function() {
  return this.setTrack(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.car.CheckInResponse.prototype.hasTrack = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional RaceType race = 6;
 * @return {!proto.car.RaceType}
 */
proto.car.CheckInResponse.prototype.getRace = function() {
  return /** @type {!proto.car.RaceType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.car.RaceType} value
 * @return {!proto.car.CheckInResponse} returns this
 */
proto.car.CheckInResponse.prototype.setRace = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.PlayerInput.prototype.toObject = function(opt_includeInstance) {
  return proto.car.PlayerInput.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.PlayerInput} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.PlayerInput.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
authToken: jspb.Message.getFieldWithDefault(msg, 2, ""),
steering: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
throttle: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
brake: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
timestamp: jspb.Message.getFieldWithDefault(msg, 99, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.PlayerInput}
 */
proto.car.PlayerInput.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.PlayerInput;
  return proto.car.PlayerInput.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.PlayerInput} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.PlayerInput}
 */
proto.car.PlayerInput.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthToken(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSteering(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setThrottle(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBrake(value);
      break;
    case 99:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTimestamp(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.PlayerInput.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.PlayerInput.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.PlayerInput} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.PlayerInput.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAuthToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSteering();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getThrottle();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getBrake();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeInt32(
      99,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.PlayerInput.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.PlayerInput} returns this
 */
proto.car.PlayerInput.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string auth_token = 2;
 * @return {string}
 */
proto.car.PlayerInput.prototype.getAuthToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.PlayerInput} returns this
 */
proto.car.PlayerInput.prototype.setAuthToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional float steering = 3;
 * @return {number}
 */
proto.car.PlayerInput.prototype.getSteering = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.PlayerInput} returns this
 */
proto.car.PlayerInput.prototype.setSteering = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float throttle = 4;
 * @return {number}
 */
proto.car.PlayerInput.prototype.getThrottle = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.PlayerInput} returns this
 */
proto.car.PlayerInput.prototype.setThrottle = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float brake = 5;
 * @return {number}
 */
proto.car.PlayerInput.prototype.getBrake = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.PlayerInput} returns this
 */
proto.car.PlayerInput.prototype.setBrake = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional int32 timestamp = 99;
 * @return {number}
 */
proto.car.PlayerInput.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 99, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.PlayerInput} returns this
 */
proto.car.PlayerInput.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 99, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.InputAck.prototype.toObject = function(opt_includeInstance) {
  return proto.car.InputAck.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.InputAck} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.InputAck.toObject = function(includeInstance, msg) {
  var f, obj = {
accepted: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
reason: jspb.Message.getFieldWithDefault(msg, 2, ""),
gameLoop: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.InputAck}
 */
proto.car.InputAck.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.InputAck;
  return proto.car.InputAck.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.InputAck} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.InputAck}
 */
proto.car.InputAck.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAccepted(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGameLoop(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.InputAck.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.InputAck.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.InputAck} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.InputAck.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccepted();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGameLoop();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional bool accepted = 1;
 * @return {boolean}
 */
proto.car.InputAck.prototype.getAccepted = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.car.InputAck} returns this
 */
proto.car.InputAck.prototype.setAccepted = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string reason = 2;
 * @return {string}
 */
proto.car.InputAck.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.InputAck} returns this
 */
proto.car.InputAck.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 game_loop = 3;
 * @return {number}
 */
proto.car.InputAck.prototype.getGameLoop = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.InputAck} returns this
 */
proto.car.InputAck.prototype.setGameLoop = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CarState.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CarState.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CarState} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarState.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
status: jspb.Message.getFieldWithDefault(msg, 2, 0),
position: (f = msg.getPosition()) && proto.car.Point3D.toObject(includeInstance, f),
heading: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
speed: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
lap: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CarState}
 */
proto.car.CarState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CarState;
  return proto.car.CarState.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CarState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CarState}
 */
proto.car.CarState.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 2:
      var value = /** @type {!proto.car.CarStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = new proto.car.Point3D;
      reader.readMessage(value,proto.car.Point3D.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHeading(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSpeed(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLap(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CarState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CarState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CarState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarState.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.car.Point3D.serializeBinaryToWriter
    );
  }
  f = message.getHeading();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getSpeed();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getLap();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.CarState.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional CarStatus status = 2;
 * @return {!proto.car.CarStatus}
 */
proto.car.CarState.prototype.getStatus = function() {
  return /** @type {!proto.car.CarStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.car.CarStatus} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional Point3D position = 3;
 * @return {?proto.car.Point3D}
 */
proto.car.CarState.prototype.getPosition = function() {
  return /** @type{?proto.car.Point3D} */ (
    jspb.Message.getWrapperField(this, proto.car.Point3D, 3));
};


/**
 * @param {?proto.car.Point3D|undefined} value
 * @return {!proto.car.CarState} returns this
*/
proto.car.CarState.prototype.setPosition = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.car.CarState.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional float heading = 4;
 * @return {number}
 */
proto.car.CarState.prototype.getHeading = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setHeading = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float speed = 5;
 * @return {number}
 */
proto.car.CarState.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setSpeed = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional int32 lap = 6;
 * @return {number}
 */
proto.car.CarState.prototype.getLap = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarState} returns this
 */
proto.car.CarState.prototype.setLap = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CarPenalty.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CarPenalty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CarPenalty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarPenalty.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
reason: jspb.Message.getFieldWithDefault(msg, 2, ""),
gameTick: jspb.Message.getFieldWithDefault(msg, 3, 0),
remainingPenalty: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CarPenalty}
 */
proto.car.CarPenalty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CarPenalty;
  return proto.car.CarPenalty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CarPenalty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CarPenalty}
 */
proto.car.CarPenalty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGameTick(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRemainingPenalty(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CarPenalty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CarPenalty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CarPenalty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarPenalty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGameTick();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getRemainingPenalty();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.CarPenalty.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarPenalty} returns this
 */
proto.car.CarPenalty.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string reason = 2;
 * @return {string}
 */
proto.car.CarPenalty.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarPenalty} returns this
 */
proto.car.CarPenalty.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 game_tick = 3;
 * @return {number}
 */
proto.car.CarPenalty.prototype.getGameTick = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarPenalty} returns this
 */
proto.car.CarPenalty.prototype.setGameTick = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 remaining_penalty = 4;
 * @return {number}
 */
proto.car.CarPenalty.prototype.getRemainingPenalty = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarPenalty} returns this
 */
proto.car.CarPenalty.prototype.setRemainingPenalty = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.RaceStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.car.RaceStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.RaceStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getFieldWithDefault(msg, 1, ""),
totalLaps: jspb.Message.getFieldWithDefault(msg, 2, 0),
gameTick: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.RaceStatus}
 */
proto.car.RaceStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.RaceStatus;
  return proto.car.RaceStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.RaceStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.RaceStatus}
 */
proto.car.RaceStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalLaps(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGameTick(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.RaceStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.RaceStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.RaceStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTotalLaps();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getGameTick();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
proto.car.RaceStatus.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.RaceStatus} returns this
 */
proto.car.RaceStatus.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 total_laps = 2;
 * @return {number}
 */
proto.car.RaceStatus.prototype.getTotalLaps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceStatus} returns this
 */
proto.car.RaceStatus.prototype.setTotalLaps = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 game_tick = 3;
 * @return {number}
 */
proto.car.RaceStatus.prototype.getGameTick = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceStatus} returns this
 */
proto.car.RaceStatus.prototype.setGameTick = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.CarInterval.prototype.toObject = function(opt_includeInstance) {
  return proto.car.CarInterval.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.CarInterval} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarInterval.toObject = function(includeInstance, msg) {
  var f, obj = {
carId: jspb.Message.getFieldWithDefault(msg, 1, ""),
position: jspb.Message.getFieldWithDefault(msg, 2, 0),
laps: jspb.Message.getFieldWithDefault(msg, 3, 0),
interval: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.CarInterval}
 */
proto.car.CarInterval.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.CarInterval;
  return proto.car.CarInterval.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.CarInterval} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.CarInterval}
 */
proto.car.CarInterval.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCarId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPosition(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLaps(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setInterval(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.CarInterval.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.CarInterval.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.CarInterval} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.CarInterval.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCarId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPosition();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getLaps();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getInterval();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional string car_id = 1;
 * @return {string}
 */
proto.car.CarInterval.prototype.getCarId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.car.CarInterval} returns this
 */
proto.car.CarInterval.prototype.setCarId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 position = 2;
 * @return {number}
 */
proto.car.CarInterval.prototype.getPosition = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarInterval} returns this
 */
proto.car.CarInterval.prototype.setPosition = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 laps = 3;
 * @return {number}
 */
proto.car.CarInterval.prototype.getLaps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarInterval} returns this
 */
proto.car.CarInterval.prototype.setLaps = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional float interval = 4;
 * @return {number}
 */
proto.car.CarInterval.prototype.getInterval = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.car.CarInterval} returns this
 */
proto.car.CarInterval.prototype.setInterval = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.car.RaceUpdate.repeatedFields_ = [2,3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.car.RaceUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.car.RaceUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.car.RaceUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
raceStatus: (f = msg.getRaceStatus()) && proto.car.RaceStatus.toObject(includeInstance, f),
carsList: jspb.Message.toObjectList(msg.getCarsList(),
    proto.car.CarState.toObject, includeInstance),
penaltiesList: jspb.Message.toObjectList(msg.getPenaltiesList(),
    proto.car.CarPenalty.toObject, includeInstance),
toLeaderList: jspb.Message.toObjectList(msg.getToLeaderList(),
    proto.car.CarInterval.toObject, includeInstance),
forPositionList: jspb.Message.toObjectList(msg.getForPositionList(),
    proto.car.CarInterval.toObject, includeInstance),
gameTick: jspb.Message.getFieldWithDefault(msg, 100, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.car.RaceUpdate}
 */
proto.car.RaceUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.car.RaceUpdate;
  return proto.car.RaceUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.car.RaceUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.car.RaceUpdate}
 */
proto.car.RaceUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.car.RaceStatus;
      reader.readMessage(value,proto.car.RaceStatus.deserializeBinaryFromReader);
      msg.setRaceStatus(value);
      break;
    case 2:
      var value = new proto.car.CarState;
      reader.readMessage(value,proto.car.CarState.deserializeBinaryFromReader);
      msg.addCars(value);
      break;
    case 3:
      var value = new proto.car.CarPenalty;
      reader.readMessage(value,proto.car.CarPenalty.deserializeBinaryFromReader);
      msg.addPenalties(value);
      break;
    case 4:
      var value = new proto.car.CarInterval;
      reader.readMessage(value,proto.car.CarInterval.deserializeBinaryFromReader);
      msg.addToLeader(value);
      break;
    case 5:
      var value = new proto.car.CarInterval;
      reader.readMessage(value,proto.car.CarInterval.deserializeBinaryFromReader);
      msg.addForPosition(value);
      break;
    case 100:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGameTick(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.car.RaceUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.car.RaceUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.car.RaceUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.car.RaceUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRaceStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.car.RaceStatus.serializeBinaryToWriter
    );
  }
  f = message.getCarsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.car.CarState.serializeBinaryToWriter
    );
  }
  f = message.getPenaltiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.car.CarPenalty.serializeBinaryToWriter
    );
  }
  f = message.getToLeaderList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.car.CarInterval.serializeBinaryToWriter
    );
  }
  f = message.getForPositionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.car.CarInterval.serializeBinaryToWriter
    );
  }
  f = message.getGameTick();
  if (f !== 0) {
    writer.writeInt32(
      100,
      f
    );
  }
};


/**
 * optional RaceStatus race_status = 1;
 * @return {?proto.car.RaceStatus}
 */
proto.car.RaceUpdate.prototype.getRaceStatus = function() {
  return /** @type{?proto.car.RaceStatus} */ (
    jspb.Message.getWrapperField(this, proto.car.RaceStatus, 1));
};


/**
 * @param {?proto.car.RaceStatus|undefined} value
 * @return {!proto.car.RaceUpdate} returns this
*/
proto.car.RaceUpdate.prototype.setRaceStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.clearRaceStatus = function() {
  return this.setRaceStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.car.RaceUpdate.prototype.hasRaceStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated CarState cars = 2;
 * @return {!Array<!proto.car.CarState>}
 */
proto.car.RaceUpdate.prototype.getCarsList = function() {
  return /** @type{!Array<!proto.car.CarState>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.CarState, 2));
};


/**
 * @param {!Array<!proto.car.CarState>} value
 * @return {!proto.car.RaceUpdate} returns this
*/
proto.car.RaceUpdate.prototype.setCarsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.car.CarState=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.CarState}
 */
proto.car.RaceUpdate.prototype.addCars = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.car.CarState, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.clearCarsList = function() {
  return this.setCarsList([]);
};


/**
 * repeated CarPenalty penalties = 3;
 * @return {!Array<!proto.car.CarPenalty>}
 */
proto.car.RaceUpdate.prototype.getPenaltiesList = function() {
  return /** @type{!Array<!proto.car.CarPenalty>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.CarPenalty, 3));
};


/**
 * @param {!Array<!proto.car.CarPenalty>} value
 * @return {!proto.car.RaceUpdate} returns this
*/
proto.car.RaceUpdate.prototype.setPenaltiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.car.CarPenalty=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.CarPenalty}
 */
proto.car.RaceUpdate.prototype.addPenalties = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.car.CarPenalty, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.clearPenaltiesList = function() {
  return this.setPenaltiesList([]);
};


/**
 * repeated CarInterval to_leader = 4;
 * @return {!Array<!proto.car.CarInterval>}
 */
proto.car.RaceUpdate.prototype.getToLeaderList = function() {
  return /** @type{!Array<!proto.car.CarInterval>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.CarInterval, 4));
};


/**
 * @param {!Array<!proto.car.CarInterval>} value
 * @return {!proto.car.RaceUpdate} returns this
*/
proto.car.RaceUpdate.prototype.setToLeaderList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.car.CarInterval=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.CarInterval}
 */
proto.car.RaceUpdate.prototype.addToLeader = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.car.CarInterval, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.clearToLeaderList = function() {
  return this.setToLeaderList([]);
};


/**
 * repeated CarInterval for_position = 5;
 * @return {!Array<!proto.car.CarInterval>}
 */
proto.car.RaceUpdate.prototype.getForPositionList = function() {
  return /** @type{!Array<!proto.car.CarInterval>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.car.CarInterval, 5));
};


/**
 * @param {!Array<!proto.car.CarInterval>} value
 * @return {!proto.car.RaceUpdate} returns this
*/
proto.car.RaceUpdate.prototype.setForPositionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.car.CarInterval=} opt_value
 * @param {number=} opt_index
 * @return {!proto.car.CarInterval}
 */
proto.car.RaceUpdate.prototype.addForPosition = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.car.CarInterval, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.clearForPositionList = function() {
  return this.setForPositionList([]);
};


/**
 * optional int32 game_tick = 100;
 * @return {number}
 */
proto.car.RaceUpdate.prototype.getGameTick = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 100, 0));
};


/**
 * @param {number} value
 * @return {!proto.car.RaceUpdate} returns this
 */
proto.car.RaceUpdate.prototype.setGameTick = function(value) {
  return jspb.Message.setProto3IntField(this, 100, value);
};


/**
 * @enum {number}
 */
proto.car.RaceType = {
  HOTLAP: 0,
  QUALY: 1,
  RACEBYLAPS: 2,
  RACEBYTIME: 3
};

/**
 * @enum {number}
 */
proto.car.CarStatus = {
  NOTREADY: 0,
  WAITING: 1,
  RACING: 2,
  SERVINGPENALTY: 3,
  FINISHED: 99
};

goog.object.extend(exports, proto.car);
